WeShop/Controllers/ClassifyController.cs
using Shop.IService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Model;
namespace WeShop.Controllers
{
    public class ClassifyController : Controller
    {
        public ISortService SortService { get; set; }
        public IProSortService ProSortService { get; set; }
        // GET: Classify
        public ActionResult Index()
        {
            List<Sort> SortResult = SortService.GetEntities(x => true).ToList();
            ViewBag.Sort = SortResult.ToList();

            //var SortResult = SortService.GetEntities(x => true).ToList();
            //ViewBag.Sort = SortResult;


            //var ProSortResult = ProSortService.GetEntities(x => true).OrderByDescending(x => x.SortCode).Take(2);
            //ViewBag.ProSort = ProSortResult.ToList();

            //var ProSortResult = ProSortService.GetEntities(x => x.SortCode == SortResult[0].Code).ToList();
            //ViewBag.ProSort = ProSortResult;

            var s = ProSortService.GetEntities(x => x.SortCode == SortResult[0].Code);
            ViewBag.ProSort = s;
            return View();
        }
        public ActionResult ProSortdata()
        {
            string id = Request["id"];
            List<ProSort> s = ProSortService.GetEntities(a => a.SortCode == id).ToList();
            string shtml = "";
            foreach(ProSort item in s )
            {
                //shtml += @"<li>
                //            <a class='imga' href='#'><img src='~/images/'" + item.Pimg + @"''></a>
                //              <a class='txta' href='#'>
                //              <span>" + item.Pname + @"</span>
                //             <i>" + item.Pcontent + @"</i>
                //             </a>
                //            </li>";
                shtml += "<li>" +
                    "<a class='imga' href='/List/Index'><img src='/images/" + @item.Pimg + "'</a>" +
                    "  <a class='txta' href='/List/Index'>" +
                    " <span>" + @item.Pname + "</span>" +
                    "  <i>" + @item.Pcontent + "</i>" +
                    "</a>" +
                    "</li>";
            }
            return Content(shtml);
        }
    }
}

WeShop/Controllers/FamilyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Senparc.Weixin.MP.AdvancedAPIs.OAuth;
using WeicharDemo.Fiters;


namespace WeShop.Controllers
{
    public class FamilyController : Controller
    {
        // GET: Family
        public ActionResult Index()
        {
            var userInfo = Session["userInfo"] as OAuthUserInfo;
            return View(userInfo);
           
        }
    }
}

WeShop/Controllers/HomeController.cs
using Shop.IService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeShop.Controllers
{
    /// <summary>
    /// 商城首页
    /// </summary>
    public class HomeController : Controller
    {
        public IBannerService BannerService { get; set; }
        public IProductService ProductService { get; set; }
        public INoticeService NoticeService { get; set; }
        // GET: Home
        /// <summary>
        /// 首页数据查询
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //查询Banner,从数据库中查询
            //ui层，不能直接实例化BLL，应该利用IBLL
            var BannerResult = BannerService.GetEntities(x => true);
            ViewBag.Banner = BannerResult.ToList();
            //产品查询
            var Productresult = ProductService.GetEntities(x => true).OrderByDescending(x => x.Time).Take(3);
            ViewBag.Product = Productresult.ToList();
            //通知查询
            var NoticeResult = NoticeService.GetEntities(x => true);
            ViewBag.Notice = NoticeResult.ToList();

            return View();
        }
        //搜索
        public ActionResult Search()
        {
            return PartialView();
        }
    }
}

WeShop/Controllers/ListController.cs
using System;
using Shop.IService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeShop.Controllers
{
    public class ListController : Controller
    {
        public IProductService ProductService { get; set; }
        // GET: List
        public ActionResult Index()
        {
            //产品查询
            var Productresult = ProductService.GetEntities(x => true)/*.OrderByDescending(x => x.Time).Take(2)*/;
            ViewBag.Product = Productresult.ToList();
            return View();
        }
    }
}

WeShop/Controllers/OAuthController.cs
using System;
using System.Web.Mvc;
using System.Configuration;
using Senparc.Weixin;
using Senparc.Weixin.MP;
using Senparc.Weixin.MP.AdvancedAPIs.OAuth;
using Senparc.Weixin.MP.Helpers;
using Senparc.Weixin.MP.AdvancedAPIs;

namespace WeShop.Controllers
{
    public class OAuthController : Controller
    {
        // GET: OAuth 生成授权页面   ---同意授权
        //1:方法中需要AppId Appsecret
        public static readonly string appID = ConfigurationManager.AppSettings["appID"];
        public static readonly string appsecret = ConfigurationManager.AppSettings["appsecret"];
        public static readonly string Domin = "http://wx.zjc916.xin";
        public ActionResult Index(string returnUrl)
        {
            //微信中需要使用的地址都是外网地址  域名/returnUrl
            //1：构造带有域名的回调Url 地址需要在函数中带有 $表示变量的占位符
            string callBackUrl = $"http://wx.zjc916.xin{Url.Action("CallBack", new { returnUrl })}";
            string state = "wx" + DateTime.Now.Millisecond;
            //保存状态参数
            Session["state"] = state;
            string oauthorurl = OAuthApi.GetAuthorizeUrl(appID, callBackUrl, state, OAuthScope.snsapi_userinfo);
            //跳转到授权页面
            return Redirect(oauthorurl);
        }
        /// <summary>
        /// 回调函数
        /// </summary>
        /// <returns></returns>
        public ActionResult CallBack(string code, string state, string returnUrl)
        {
            //注意:前提是先要判断用户输入进来的数据state是否满足
            if (Session["state"]?.ToString() != state)
            {
                Session["State"] = null;
                return Content("非安全方式登陆，登陆失败，请重新进入");

            }
            //把session中的数据清理
            Session["state"] = null;

            //判断用户返回的code
            if (string.IsNullOrEmpty(code))
            {
                return Content("未点击商城网址");
            }
            //以token换取accesstoken
            var accessToken = OAuthApi.GetAccessToken(appID, appsecret, code);

            if (accessToken.errcode != ReturnCode.请求成功)
            {
                //需要重新定位到授权页面
                return Content($"错误消息:{accessToken.errmsg}");
            }
            Session["authonAccessToken"] = accessToken;
            //以token 和oppenid来换取用户消息
            try
            {
                OAuthUserInfo usrinfo = OAuthApi.GetUserInfo(accessToken.access_token, accessToken.openid);
                Session["userInfo"] = usrinfo;
                return Redirect(returnUrl);
            }
            catch (Exception)
            {
                //如果是没有获取到用户的信息,则需要进入到授权页面
                var callBackUrl = $"http://wx.minwebsite.xin{Url.Action("Callback", new { returnUrl })}";
                // 随机数，用于加强回调请求的安全，避免被恶意请求，类似验证码
                state = "wx" + DateTime.Now.Millisecond;
                Session["State"] = state;


                var url = OAuthApi.GetAuthorizeUrl(appID, callBackUrl, state, OAuthScope.snsapi_userinfo);
                return Redirect(url);

            }

        }
        /// <summary>
        /// js-sdk 注入接口配置
        /// </summary>
        /// <returns></returns>
        public ActionResult JsSdkConfig()
        {
            //构造url地址，注意是包含域名的
            string url = $"{Domin}{Request.RawUrl}";
            JsSdkUiPackage jssdkuipackage = JSSDKHelper.GetJsSdkUiPackage(appID, appsecret, url);
            return PartialView(jssdkuipackage);
        }
    }
}

WeShop/Views/Classify/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout.cshtml";
}
@using Shop.Model;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta name="description" content="Free Web tutorials">
    <meta name="keywords" content="HTML,CSS,JavaScript">
    <meta content="telephone=no" name="format-detection">
    <title>老凤祥珠宝</title>
    <link href="~/css/Cbase.css" type="text/css" rel="stylesheet">
    <link href="~/css/index.css" type="text/css" rel="stylesheet">
    <link href="~/css/swiper.min.css" type="text/css" rel="stylesheet">
    <script src="~/js/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="~/js/base.js" type="text/javascript"></script>
    <script src="~/js/swiper.min.js" type="text/javascript"></script>
    <script src="~/js/index.js" type="text/javascript"></script>
    <title>ClassifyIndex</title>
    <script>
    $(function()
    {
        $(".on").click(function(){
           // alert($(this).attr("dataid"))
            $.ajax({
                type: "post",
                url: "@Url.Action("ProSortdata", "Classify")",
                data: { "id": $(this).attr("dataid") },
                success: function (data) {
                    $(".fenlist").html('<ul id="fl">' + data + '</ul>')
                }
            })
        })
        $(".con").click(function () {
           // alert($(this).attr("dataid"))
            $.ajax({
                type: "post",
                url: "@Url.Action("ProSortdata", "Classify")",
                data: { "id": $(this).attr("dataid") },
                success: function (data) {
                    $(".fenlist").html('<ul id="fl">' + data + '</ul>')
                }
            })
        })
    })
    </script>
</head>

<body>
    <div class="ftop">
        <div class="index_search index_search01" style="padding-left: 10px;">
            <div style="left:0px; width:100%;" onclick="document.location='search.html'">
                <input type="text" placeholder="请输入您要搜索的产品">
                <input type="button" value=" ">
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <!--ftop开始-->
    <!--分类页面-->
    <!--分类-->
    <div class="fenlei">
        <div class="fen-nav">

            <ul>
                @{int i = 0;

                    foreach (var  item in ViewBag.Sort)
                    {
                        if (i == 0)
                        {
                            <li class="on" dataid="@item.Code">@item.Name</li>
                        }
                        else
                        {
                            <li class="con" dataid="@item.Code">@item.Name</li>
                        }
                            i++;

                        }
                    }

               
            </ul>
        </div>
        <div class="fen-box">
            <div class="fff">
                <div class="fenlist">
                    <ul id="f1">
                        @foreach(var item in ViewBag.ProSort)
                        {
                            <li>
                                <a class="imga" href="/Product/Index/?id=@item.SortCode"><img src="~/images/@item.Pimg"></a>
                                <a class="txta" href="/Product/Index/?id=@item.SortCode">
                                    <span>@item.Pname</span>
                                    <i>@item.Pcontent</i>
                                   
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
  
    <!--分类-->
    <!--分类页面-->
    <!--fixft开始-->
    <div class="fixft">
        <a href="index.html"><span><img src="images/navicon_45.png" class="img1"><img src="images/navicon_28.png" class="img2"></span> <i>首页</i></a>
        <a href="publish.html" class="current"><span><img src="images/navicon_48.png" class="img1"><img src="images/navicon_30.png" class="img2"></span> <i>分类</i></a>
        <a href="shopcar.html"><span><img src="images/navicon_50.png" class="img1"><img src="images/navicon_32.png" class="img2"><em>12</em></span> <i>购物车</i></a>
        <a href="center.html"><span><img src="images/navicon_42.png" class="img1"><img src="images/navicon_35.png" class="img2"></span> <i>我的</i></a>
    </div>
    <!--fixft结束-->


    <script>
    var m=$(window).height()-98;
    $(".fen-nav,.fen-box").css("height",m+"px");


    var $lii = $(".fenlei .fen-nav li");
    $(".fenlei .fen-box .fenlist").hide();
    $(".fenlei .fen-box .fenlist").first().show();
    $lii.click(function(){
        var n = $(this).index();
        var h = $(this).height();
        //alert(h)
        var sunh = n * h-1;
        $(".fen-nav").animate({"scrollTop":sunh+"px"},1000)


        $(this).addClass("on").siblings().removeClass("on");
        var indexx = $lii.index(this);
        $('.fenlei .fen-box').animate({scrollTop: '0px'},500);
       //$(".fenlei .fen-box .fff .fenlist").hide();
        $(".fenlei .fen-box .fff .fenlist").eq(indexx).show();
    })
    var w=$(".fenli li img").width();
    $(".fenli li img").height(w);
    $(window).resize(function(){
        var w=parseInt($(".fenli li img").width());
        $(".fenli li img").height(w);
    })

    </script>



</body>
</html>

WeShop/Views/Family/Index.cshtml
@model Senparc.Weixin.MP.AdvancedAPIs.OAuth.OAuthUserInfo
    @Html.Action("index","Home")

WeShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout ="~/Views/Layout.cshtml";
}
@using Shop.Model
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta name="description" content="Free Web tutorials">
    <meta name="keywords" content="HTML,CSS,JavaScript">
    <meta content="telephone=no" name="format-detection">
    <title>老凤祥珠宝</title>
    @*<link href="css/Cbase.css" type="text/css" rel="stylesheet">*@
    <link href="~/css/Cbase.css" rel="stylesheet" />
    @*<link href="css/index.css" type="text/css" rel="stylesheet">*@
    <link href="~/css/index.css" rel="stylesheet" />
    @*<link href="css/swiper.min.css" type="text/css" rel="stylesheet">*@
    <link href="~/css/swiper.min.css" rel="stylesheet" />
    @*<script src="js/jquery-1.7.2.min.js" type="text/javascript"></script>*@
    <script src="~/js/jquery-1.7.2.min.js"></script>
    @*<script src="js/base.js" type="text/javascript"></script>*@
    <script src="~/js/base.js"></script>
    @*<script src="js/swiper.min.js" type="text/javascript"></script>*@
    <script src="~/js/swiper.min.js"></script>
    @*<script src="js/index.js" type="text/javascript"></script>*@
    <script src="~/js/index.js"></script>
</head>

<body>
    <!--ftop开始-->
    <div class="ftop">
        <div class="index_search">
            <input onclick="document.location='search.html'" type="text" placeholder="请输入您要搜索的产品">
            <p><a href="gonggao.html"><img src="images/icon_05.png"><sup>11</sup></a></p>
        </div>
        <div style="clear: both;"></div>
    </div>
    <!--ftop开始-->
    <!--banner start-->
    <div class="swiper-container index_banner">
        <div class="swiper-wrapper">
            @*<div class="swiper-slide"><a><img src="~/images/index.jpg" /></a></div>*@
            @*<div class="swiper-slide"><a><img src="images/index_img01.jpg" alt=""></a></div>
            <div class="swiper-slide"><a><img src="images/index_img03.jpg" alt=""></a></div>*@
            @foreach(Banner item in ViewBag.Banner as List<Banner>)
            {
                <div class="swiper-slide">
                    <a>
                        <img src="~/images/@item.Image" alt=""/>
                    </a>
                </div>
            }
        </div>
            <div class="swiper-pagination swiper-index"></div>
        </div>
    <script>
	var swiper1 = new Swiper('.index_banner', {
		pagination: '.swiper-index',
		paginationClickable: true,
		loop: true,
		autoplay: 4000,
	});
    </script>
    <!--banner over-->
    <div class="index_knowledge">
        <img src="~/images/gonggao.png">
        <div class="swiper-container dlist">
            <div class="swiper-wrapper">
                @foreach (Notice item in ViewBag.Notice as List<Notice>)
                {
                    <a class="swiper-slide" href="gonggao_xq.html">
                        <i>@item.Title</i>
                        @item.Body
                    </a>                          
                }
                @*<a class="swiper-slide" href="gonggao_xq.html"><i>最新</i>one冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补...</a>
                <a class="swiper-slide" href="gonggao_xq.html"><i>最热</i>two冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补...</a>
                <a class="swiper-slide" href="gonggao_xq.html"><i>最新</i>three冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补...</a>*@
            </div>
        </div>
    </div>
    <script>
  var swiper1 = new Swiper('.dlist', {
    loop: true,
    autoplay: 4000,
    direction : 'vertical'
  });
    </script>
    <div class="index_main">
        <p class="index_mtitle"> <a class="on" href="#">热销</a> <a href="#">推荐</a> <a href="index_xianshi.html">限时</a></p>
        <ul>
            @*<li>
                <a href="product_xq.html"><img src="images/index_img01.jpg"></a>
                <div class="product_text">
                    <h2>
                        <p>特级云南冬虫夏草</p>
                        <span><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_07.png"></span>
                    </h2>
                    <p>冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。</p>
                    <h3>
                        <p><i>￥</i><b>180.00</b><span>特级</span><span>甄选</span></p>
                        <a href="product_xq.html">立即购买</a>
                    </h3>
                </div>
            </li>*@
            @foreach (Product item in ViewBag.Product)
        {
            <li>
                <a href="product_xq.html"><img src="~/images/@item.Image"></a>
                <div class="product_text">
                    <h2>
                        <p>@item.Name</p>
                        <span><img src="~/images/icon_06.png" /><img src="~/images/icon_06.png" /><img src="~/images/icon_06.png" /><img src="~/images/icon_06.png" /><img src="~/images/icon_07.png"></span>
                    </h2>
                    <p>@item.describe</p>
                    <h3>
                        <p><i>￥</i><b>@item.price</b><span>特级</span><span>甄选</span></p>
                        <a href="product_xq.html">立即购买</a>
                    </h3>
                </div>
            </li>
        }
            @*<li>
                <a href="product_xq.html"><img src="images/index_img02.jpg"></a>
                <div class="product_text">
                    <h2>
                        <p>特级云南冬虫夏草</p>
                        <span><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_07.png"></span>
                    </h2>
                    <p>冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。</p>
                    <h3>
                        <p><i>￥</i><b>180.00</b><span>特级</span><span>甄选</span></p>
                        <a href="product_xq.html">立即购买</a>
                    </h3>
                </div>
            </li>
            <li>
                <a href="product_xq.html"><img src="images/index_img03.jpg"></a>
                <div class="product_text">
                    <h2>
                        <p>特级云南冬虫夏草</p>
                        <span><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_06.png"><img src="images/icon_07.png"></span>
                    </h2>
                    <p>冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。</p>
                    <h3>
                        <p><i>￥</i><b>180.00</b><span>特级</span><span>甄选</span></p>
                        <a href="product_xq.html">立即购买</a>
                    </h3>
                </div>
            </li>*@
        </ul>
    </div>
    <div class="index_icon">
        <p>
          
            <span><img src="~/images/icon_01.png" /><i>品质保证</i></span>
            <span><img src="~/images/icon_02.png"><i>送货保障</i></span>
            <span><img src="~/images/icon_003.png"><i>7天包换</i></span>
            <span><img src="~/images/icon_04.png"><i>质量保障</i></span>
        </p>
    </div>
</body>
</html>

WeShop/Views/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta name="description" content="Free Web tutorials">
    <meta name="keywords" content="HTML,CSS,JavaScript">
    <meta content="telephone=no" name="format-detection">
    <title>老凤祥珠宝</title>
    <link href="~/css/Cbase.css" rel="stylesheet" />
    <link href="~/css/index.css" rel="stylesheet" />
    <link href="~/css/swiper.min.css" rel="stylesheet" />
    <script src="~/js/jquery-1.7.2.min.js"></script>
    <script src="~/js/base.js"></script>
    <script src="~/js/swiper.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("styles",false)
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <!--fixft开始-->
    <div class="fixft">
        <a href="/Home/Index" class="current">
            <span><img src="~/images/navicon_45.png" class="img1"><img src="~/images/navicon_28.png" class="img2"></span>
            <i>首页</i>
        </a>
        <a href="/Classify/Index">
            <span><img src="~/images/navicon_48.png" class="img1"><img src="~/images/navicon_30.png" class="img2"></span>
            <i>分类</i>
        </a>
        <a href="shopcar.html">
            <span><img src="~/images/navicon_50.png" class="img1"><img src="~/images/navicon_32.png" class="img2"><em>12</em></span>
            <i>购物车</i>
        </a>
        <a href="center.html">
            <span><img src="~/images/navicon_42.png" class="img1"><img src="~/images/navicon_35.png" class="img2"></span>
            <i>我的</i>
        </a>
    </div>
    <!--fixft结束-->
</body>
</html>

WeShop/Views/List/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout.cshtml";
}

<!DOCTYPE html>
@using Shop.Model;
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <!--ftop开始-->
    <div class="ftop">
        <div class="index_search index_search01">
            <a class="back" onClick="javascript:history.back(-1);"><img src="images/icon_03.png"></a>
            <div>
                <input type="text" placeholder="请输入您要搜索的产品">
                <input class="dw" onclick="document.location='search_list.html'" type="button" value=" ">
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <!--ftop开始-->
    <div class="search_list">
        <p><a class="on"><span>综合</span></a><a><span>销量</span></a><a><span>评价</span></a><a><span class="bg">价格</span></a></p>
        <ul>
            @foreach (Product item in ViewBag.Product)
            {
                <li>
                    <a href="product_xq.html">
                        <img src="~/images/@item.Image">
                        <div class="search_item">                         
                                <p>@item.Name</p>
                                <h2><i>￥</i><b>@item.price</b><span>@item.contents</span></h2>
                        </div>
                    </a>
                </li>
            }
            @*<li>
        <a href="product_xq.html">
            <img src="images/img_010.jpg">
            <div class="search_item">
                <p>云南特级冬虫夏草云南特级冬虫夏草</p>
                <h2><i>￥</i><b>185.00</b><span>月销18252笔</span></h2>
            </div>
        </a>
    </li>*@
        </ul>
    </div>
    <script>
    $(".search_list ul li a img").each(function(){
        var w = $(this).width();
        $(this).height(w+"px");
    })

    </script>


</body>
</html>

WeShop/Views/OAuth/JsSdkConfig.cshtml
@*分部视图，因为在所有需要使用JS-SDK的页面必须先注入配置信息*@
@model Senparc.Weixin.MP.Helpers.JsSdkUiPackage
<script>
    wx.config({

        debug: false, @*开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。*@

        appId: '@Model.AppId', @*// 必填，公众号的唯一标识*@

    timestamp:@Model.Timestamp ,@*// 必填，生成签名的时间戳*@

    nonceStr: '@Model.NonceStr', @*// 必填，生成签名的随机串*@

    signature: '@Model.Signature',@*// 必填，签名，见附录1*@

        jsApiList: ['onMenuShareTimeline','chooseImage','openLocation','getLocation','scanQRCode'


    ]  @*// 必填，需要使用的JS接口列表，所有JS接口列表见附录2*@

    });
</script>